startDate <- strptime("2007-02-01", format="%Y-%m-%d")
endDate <- strptime("2007-02-03", format="%Y-%m-%d")
powerConsumption <- read.table("household_power_consumption.txt", sep=";",na.strings=c("?"), header=T)
powerConsumption$DateTime <- strptime(paste(powerConsumption$Date, powerConsumption$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
powerConsumption <- powerConsumption[powerConsumption$DateTime >= startDate & powerConsumption$DateTime < endDate, ]
par(mfrow = c(1,1))
plot(powerConsumption$DateTime, powerConsumption$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(powerConsumption$DateTime, powerConsumption$Sub_metering_2, type="l", col="red")
lines(powerConsumption$DateTime, powerConsumption$Sub_metering_3, type="l", col="blue")
legend(x="topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty=1)
dev.copy(png, file="./plot3.png", width=633)
dev.off()